#!/bin/bash
sudo su
yum update -y
#### to install httpd apache server
yum install -y httpd.x86_64
systemctl start httpd.service
systemctl enable httpd.service
echo "hello world from $(hostname -f)">/var/www/html/index.html
